In [285]:
import random
import time
class Randwalker:

    def __init__(self):
        self.position=0

    def walk(self,n):
        for i in range(n):
            yield self.position
            self.position= self.position+2*random.randint(0,1)-1
start=time.perf_counter()        
walker=Randwalker()
walk=[position for position in walker.walk(1000)]
end=time.perf_counter()
print(f"took {end-start} seconds")


took 0.003564739000012196 seconds


# with out classes

In [286]:
def walk(n):
    position=0
    for i in range(n):
        
        yield position
        position+=2*random.randint(0,1)-1
        
start=time.perf_counter()        
walk=[position for position in walk(1000)]
end=time.perf_counter()
print(f"took {end-start} seconds")

took 0.0031555559999105753 seconds


making it as function does not reduced execution time

# using numpy

In [287]:

import numpy as np

def fast_walker(n):
    steps=np.random.choice([-1,1],n)
    return np.cumsum(steps)

start=time.perf_counter()
fast_walker(1000)
end=time.perf_counter()

print(f"took {end-start} seconds")


took 0.0003391240002201812 seconds


how cum sum works


In [288]:
print(np.cumsum([0,1,2,3,4]))

[ 0  1  3  6 10]


how choice works

In [289]:
print (np.random.choice([1,2,3],100))

[3 2 3 3 2 2 3 1 3 1 1 1 2 1 2 3 3 3 2 3 2 2 2 3 1 3 3 1 2 1 1 3 3 1 1 2 1
 2 1 1 3 2 1 2 3 3 3 2 2 2 1 1 3 2 2 2 2 2 3 3 2 1 1 2 3 1 3 2 1 1 3 2 3 1
 2 3 2 1 2 1 1 1 3 2 3 2 3 1 3 3 3 1 1 1 2 3 3 2 3 3]


why numpy not lists

very fast

contigous memory

simd processing


effective cache

# getting started

In [290]:
import numpy as np

a=np.array([1,2,3])
b=np.array([1,2,3])
print (a*b)

[1 4 9]


In [291]:
a=np.array([1,2,3])
b=np.array([4])
print (a*b)

[ 4  8 12]


In [292]:
a=np.array([1,2,3])
b=np.array([5])
print (a*b)

[ 5 10 15]


In [293]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [294]:
a.ndim

1

In [295]:
a.shape

(3,)

In [296]:
b.shape

(1,)

In [297]:
c.shape

(2, 3)

In [298]:
c.ndim

2

In [299]:
a.dtype

dtype('int64')

In [300]:
b=np.array([1,2,3],dtype='int8')

In [301]:
b.dtype

dtype('int8')

In [302]:
a.itemsize

8

In [303]:
b.itemsize

1

In [304]:
a.size

3

In [305]:
c.size

6

In [306]:
c.itemsize

8

In [307]:
f"number of bytes in c={c.size*c.itemsize}"

'number of bytes in c=48'

In [308]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [309]:
a[1,-1]

12

In [310]:
a[1,5]

12

In [311]:
a[1,3]

10

In [312]:
a[0,-1]

6

In [313]:
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [314]:
a[:,3:6]

array([[ 4,  5,  6],
       [10, 11, 12]])

start:end:step
        

In [315]:
a[:,2:5:2]

array([[ 3,  5],
       [ 9, 11]])

In [316]:
a[1,-1]=20

In [317]:
a


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 20]])

In [318]:
a[:,2]=[1,2]

In [319]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20]])

In [320]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [321]:
np.zeros(5).itemsize

8

In [322]:
np.zeros(5,dtype='int32')

array([0, 0, 0, 0, 0], dtype=int32)

In [323]:
np.zeros(5,dtype='int32').itemsize

4

In [324]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [325]:
np.zeros((3,4),dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [326]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [327]:
np.ones((4,3,2),dtype="int8")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [328]:
np.full((2,2),99,dtype=int)

array([[99, 99],
       [99, 99]])

In [329]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [330]:
np.full_like(a,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [331]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [332]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1]])

In [333]:
np.random.rand(3,3,3,3)

array([[[[9.96357455e-01, 5.51809533e-02, 1.70046048e-01],
         [7.12108237e-01, 4.19509860e-01, 6.74365122e-01],
         [4.33491295e-01, 2.86677831e-01, 5.87483760e-01]],

        [[5.53448241e-01, 1.07875000e-01, 7.52087294e-01],
         [3.98766744e-01, 9.09321383e-01, 9.97297695e-01],
         [1.51257877e-01, 6.51755216e-01, 1.44056992e-01]],

        [[1.08207475e-01, 3.83830403e-01, 4.91202606e-01],
         [9.28428508e-04, 7.46564504e-01, 1.68880907e-01],
         [6.58658159e-01, 1.21283555e-01, 3.40304138e-01]]],


       [[[8.36877982e-01, 8.88701476e-01, 3.84342938e-01],
         [7.48336753e-01, 8.77749056e-01, 3.04408976e-01],
         [8.29545877e-01, 7.53106664e-01, 2.92376544e-01]],

        [[6.22119022e-01, 6.89178698e-01, 6.19138096e-01],
         [5.96810621e-01, 7.87027366e-01, 6.22585685e-01],
         [8.20770893e-01, 5.42755303e-01, 7.60183106e-01]],

        [[7.66547310e-01, 2.66222312e-01, 4.23644349e-01],
         [4.78533335e-02, 9.94396468e-01, 7.

In [334]:
np.random.rand(3,3)

array([[0.99696445, 0.62690206, 0.57436171],
       [0.80997146, 0.00836401, 0.10142806],
       [0.88085513, 0.38211596, 0.07481723]])

In [335]:
np.random.random_sample(a.shape)

array([[0.74104381, 0.39739616, 0.13095961, 0.91103457, 0.46683171,
        0.91098952],
       [0.57911562, 0.51640567, 0.53402293, 0.45079021, 0.43239537,
        0.22207939]])

In [336]:
np.random.randint(0,1)

0

In [337]:
np.random.randint(0,1)

0

In [338]:
np.random.randint(0,1)

0

In [339]:
np.random.randint(4,size=(3,4))

array([[2, 3, 2, 0],
       [3, 2, 3, 0],
       [2, 2, 1, 3]])

In [340]:
np.random.randint(4,8,size=(3,4))

array([[6, 7, 6, 5],
       [4, 6, 5, 4],
       [7, 5, 7, 4]])

In [341]:
np.random.randint(0,1)

0

In [342]:
np.random.randint(0,1)

0

In [343]:
np.random.randint(0,1)

0

In [344]:
np.random.randint(0,1)

0

In [345]:
np.random.randint(0,1)

0

In [346]:
np.random.randint(0,1)

0

In [347]:
np.random.randint(0,1)

0

In [348]:
np.random.randint(0,1)

0

In [349]:
np.random.randint(0,2)

0

In [350]:
np.random.randint(0,2)

0

In [351]:
np.random.randint(0,2)

1

end is not inclusive

In [352]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [353]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [354]:
ar=np.repeat(a,3)

In [355]:
ar

array([ 1,  1,  1,  2,  2,  2,  1,  1,  1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  2,  2,  2, 10, 10, 10, 11, 11, 11, 20,
       20, 20])

In [356]:
ar=np.repeat(a,3,axis=0)

In [357]:
ar

array([[ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20]])

In [358]:
a.shape

(2, 6)

In [359]:
np.repeat(a,6,axis=0)

array([[ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20]])

In [360]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20]])

In [361]:
np.repeat(a,3)

array([ 1,  1,  1,  2,  2,  2,  1,  1,  1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  2,  2,  2, 10, 10, 10, 11, 11, 11, 20,
       20, 20])

In [362]:
a=np.ones((5,5),dtype=int)


In [363]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [364]:
b=np.zeros((3,3),dtype=int)

In [365]:
b[1,1]=9

In [366]:
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [367]:
a[1:-1,1:-1]=b

In [368]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [369]:
b=a


In [370]:
b[0,0]=5


In [371]:
a

array([[5, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [372]:
a=np.array([1,2,3])
print(a+2)

[3 4 5]


In [373]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

##### linear algebra

In [374]:
a=np.ones((2,3))

In [375]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [376]:
b=np.ones((3,2))*2

In [377]:
b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [378]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [379]:
np.linalg.det(np.matmul(a,b))

0.0

In [380]:
np.linalg.pinv(a)

array([[0.16666667, 0.16666667],
       [0.16666667, 0.16666667],
       [0.16666667, 0.16666667]])

In [381]:
a=np.ones((3,3))

In [382]:
np.linalg.eig(a)

(array([-2.22044605e-16,  3.00000000e+00,  0.00000000e+00]),
 array([[-0.81649658,  0.57735027,  0.        ],
        [ 0.40824829,  0.57735027, -0.70710678],
        [ 0.40824829,  0.57735027,  0.70710678]]))

In [383]:
a=[[1,2,3],[4,5,6]]
np.min(a)

1

In [384]:
np.max(a)

6

In [385]:
a=np.repeat(a,1)

In [386]:
a

array([1, 2, 3, 4, 5, 6])

In [387]:
np.random.choice(a)

2

In [388]:
np.random.choice(a)

2

In [389]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

# reorganising array

In [390]:
a=np.array([[1,2,3],[4,5,6]])

In [391]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

hstack vstack

np.genfrom(txt)

# boolean indexing

In [392]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [393]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [394]:
a[a>4]

array([5, 6, 7, 8, 9])

In [395]:
a[[2,-1,3]]

array([3, 9, 4])

# from python to numpy

In [396]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [397]:
z=np.ones(9)

In [398]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [399]:
z=np.ones((1,40),dtype='int32')

In [400]:
z.itemsize

4

In [401]:
type(z[0,1])


numpy.int32

In [402]:
z.size

40

In [403]:
z.view('float64')

array([[2.12199579e-314, 2.12199579e-314, 2.12199579e-314,
        2.12199579e-314, 2.12199579e-314, 2.12199579e-314,
        2.12199579e-314, 2.12199579e-314, 2.12199579e-314,
        2.12199579e-314, 2.12199579e-314, 2.12199579e-314,
        2.12199579e-314, 2.12199579e-314, 2.12199579e-314,
        2.12199579e-314, 2.12199579e-314, 2.12199579e-314,
        2.12199579e-314, 2.12199579e-314]])

In [404]:
z.itemsize

4

In [405]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [406]:
type(z[0,0])

numpy.int64

In [407]:
z=z.astype('int8')
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int8)

In [408]:
type(z[0,0])

numpy.int8

In [409]:
z.size

9