In [1]:
import random
import time
class Randwalker:

    def __init__(self):
        self.position=0

    def walk(self,n):
        for i in range(n):
            yield self.position
            self.position= self.position+2*random.randint(0,1)-1
start=time.perf_counter()        
walker=Randwalker()
walk=[position for position in walker.walk(1000)]
end=time.perf_counter()
print(f"took {end-start} seconds")


took 0.005679419999978563 seconds


# with out classes

In [2]:
def walk(n):
    position=0
    for i in range(n):
        
        yield position
        position+=2*random.randint(0,1)-1
        
start=time.perf_counter()        
walk=[position for position in walk(1000)]
end=time.perf_counter()
print(f"took {end-start} seconds")

took 0.003338722000080452 seconds


making it as function does not reduced execution time

# using numpy

In [5]:

import numpy as np

def fast_walker(n):
    steps=np.random.choice([-1,1],n)
    return np.cumsum(steps)

start=time.perf_counter()
fast_walker(1000)
end=time.perf_counter()

print(f"took {end-start} seconds")


took 0.0001769720001902897 seconds


how cum sum works


In [6]:
print(np.cumsum([0,1,2,3,4]))

[ 0  1  3  6 10]


how choice works

In [7]:
print (np.random.choice([1,2,3],100))

[2 1 1 2 2 3 2 2 1 3 1 3 1 2 2 1 3 2 1 1 1 1 3 1 3 1 3 3 3 3 3 1 1 1 1 1 2
 2 3 2 1 2 3 1 1 1 1 1 3 2 1 2 1 3 2 1 2 2 2 3 3 3 1 1 2 1 3 2 2 2 1 1 2 2
 2 1 2 1 2 3 3 2 2 3 1 2 3 2 1 2 3 2 2 1 1 2 1 3 1 1]


why numpy not lists

very fast

contigous memory

simd processing


effective cache

# getting started

In [8]:
import numpy as np

a=np.array([1,2,3])
b=np.array([1,2,3])
print (a*b)

[1 4 9]


In [12]:
a=np.array([1,2,3])
b=np.array([4])
print (a*b)

[ 4  8 12]


In [13]:
a=np.array([1,2,3])
b=np.array([1,2])
print (a*b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [14]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.ndim

1

In [16]:
a.shape

(3,)

In [17]:
b.shape

(2,)

In [18]:
c.shape

(2, 3)

In [19]:
c.ndim

2

In [20]:
a.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [21]:
a.dtype

dtype('int64')

In [22]:
b=np.array([1,2,3],dtype='int8')

In [23]:
b.dtype

dtype('int8')

In [24]:
a.itemsize

8

In [25]:
b.itemsize

1

In [26]:
a.size

3

In [27]:
c.size

6

In [29]:
c.itemsize

8

In [28]:
f"number of bytes in c={c.size*c.itemsize}"

'number of bytes in c=48'

In [32]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [33]:
a[1,-1]

12

In [34]:
a[1,5]

12

In [35]:
a[1,3]

10

In [36]:
a[0,-1]

6

In [37]:
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [38]:
a[:,3:6]

array([[ 4,  5,  6],
       [10, 11, 12]])

start:end:step
        

In [40]:
a[:,2:5:2]

array([[ 3,  5],
       [ 9, 11]])

In [41]:
a[1,-1]=20

In [42]:
a


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 20]])

In [43]:
a[:,2]=[1,2]

In [44]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20]])

In [45]:
a[1,:]=[3,4]

ValueError: cannot copy sequence with size 2 to array axis with dimension 6

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros(5).itemsize

8

In [50]:
np.zeros(5,dtype='int32')

array([0, 0, 0, 0, 0], dtype=int32)

In [51]:
np.zeros(5,dtype='int32').itemsize

4

In [54]:
np.zeros(3,4,dtype='int32')

TypeError: Argument given by name ('dtype') and position (2)

In [55]:
np.zeros((3,4),dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [57]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.ones((4,3,2),dtype="int8")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [60]:
np.full((2,2),99,dtype=int)

array([[99, 99],
       [99, 99]])

In [61]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.full_like(a,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [63]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [64]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1]])

In [65]:
np.random.rand(3,3,3,3)

array([[[[0.92283783, 0.27235002, 0.10035316],
         [0.07007234, 0.90240857, 0.80189823],
         [0.25039978, 0.61748155, 0.5796299 ]],

        [[0.55382224, 0.88471696, 0.63767567],
         [0.18574236, 0.08636138, 0.34751256],
         [0.06155128, 0.12363865, 0.61870464]],

        [[0.83570404, 0.35814491, 0.78717023],
         [0.76540136, 0.17867268, 0.31354048],
         [0.57512101, 0.97187217, 0.71030715]]],


       [[[0.14117141, 0.51571613, 0.19272855],
         [0.79119182, 0.97319826, 0.06770555],
         [0.26184865, 0.74500932, 0.01420208]],

        [[0.42958137, 0.9742415 , 0.62080829],
         [0.49468931, 0.48536246, 0.11648623],
         [0.13816403, 0.97205314, 0.21074639]],

        [[0.20261352, 0.57701543, 0.11217527],
         [0.34375952, 0.99527241, 0.13161275],
         [0.79838082, 0.81310024, 0.15595021]]],


       [[[0.92234029, 0.19806557, 0.31336605],
         [0.29598005, 0.79754513, 0.59098832],
         [0.0499792 , 0.61640145, 0.1316544 

In [66]:
np.random.rand(3,3)

array([[0.32556871, 0.10719731, 0.17144416],
       [0.83541736, 0.89137011, 0.76510558],
       [0.30505221, 0.44296502, 0.25522403]])

In [67]:
np.random.random_sample(a.shape)

array([[0.27702011, 0.12415172, 0.01762658, 0.29586243, 0.09099095,
        0.88421067],
       [0.74536084, 0.45419904, 0.93700597, 0.72981835, 0.71532526,
        0.41781876]])

In [68]:
np.random.randint(0,1)

0

In [69]:
np.random.randint(0,1)

0

In [70]:
np.random.randint(0,1)

0

In [71]:
np.random.randint(4,size=(3,4))

array([[2, 3, 2, 1],
       [0, 0, 3, 2],
       [0, 1, 3, 3]])

In [72]:
np.random.randint(4,8,size=(3,4))

array([[6, 7, 4, 7],
       [4, 4, 5, 7],
       [5, 4, 4, 7]])

In [73]:
np.random.randint(0,1)

0

In [74]:
np.random.randint(0,1)

0

In [75]:
np.random.randint(0,1)

0

In [76]:
np.random.randint(0,1)

0

In [77]:
np.random.randint(0,1)

0

In [78]:
np.random.randint(0,1)

0

In [79]:
np.random.randint(0,1)

0

In [80]:
np.random.randint(0,1)

0

In [81]:
np.random.randint(0,2)

0

In [82]:
np.random.randint(0,2)

1

In [83]:
np.random.randint(0,2)

0

end is not inclusive

In [84]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [86]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
ar=np.repeat(a,3)

In [89]:
ar

array([ 1,  1,  1,  2,  2,  2,  1,  1,  1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  2,  2,  2, 10, 10, 10, 11, 11, 11, 20,
       20, 20])

In [90]:
ar=np.repeat(a,3,axis=0)

In [91]:
ar

array([[ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20]])

In [92]:
a.shape

(2, 6)

In [93]:
np.repeat(a,6,axis=0)

array([[ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20]])

In [94]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20]])

In [95]:
np.repeat(a,3)

array([ 1,  1,  1,  2,  2,  2,  1,  1,  1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  2,  2,  2, 10, 10, 10, 11, 11, 11, 20,
       20, 20])

In [100]:
a=np.ones((5,5),dtype=int)


In [101]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [104]:
b=np.zeros((3,3),dtype=int)

In [110]:
b[1,1]=9

In [111]:
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [113]:
a[1:-1,1:-1]=b

In [114]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [115]:
b=a


In [116]:
b[0,0]=5


In [117]:
a

array([[5, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])