In [1]:
import random
import time
class Randwalker:

    def __init__(self):
        self.position=0

    def walk(self,n):
        for i in range(n):
            yield self.position
            self.position= self.position+2*random.randint(0,1)-1
start=time.perf_counter()        
walker=Randwalker()
walk=[position for position in walker.walk(1000)]
end=time.perf_counter()
print(f"took {end-start} seconds")


took 0.001562657999897965 seconds


# with out classes

In [2]:
def walk(n):
    position=0
    for i in range(n):
        
        yield position
        position+=2*random.randint(0,1)-1
        
start=time.perf_counter()        
walk=[position for position in walk(1000)]
end=time.perf_counter()
print(f"took {end-start} seconds")

took 0.0011351850000664854 seconds


making it as function does not reduced execution time

# using numpy

In [3]:

import numpy as np

def fast_walker(n):
    steps=np.random.choice([-1,1],n)
    return np.cumsum(steps)

start=time.perf_counter()
fast_walker(1000)
end=time.perf_counter()

print(f"took {end-start} seconds")


took 0.00018462099990301795 seconds


how cum sum works


In [4]:
print(np.cumsum([0,1,2,3,4]))

[ 0  1  3  6 10]


how choice works

In [5]:
print (np.random.choice([1,2,3],100))

[2 2 1 3 3 3 2 2 1 3 1 2 1 2 1 3 1 3 3 3 1 2 1 1 3 3 2 3 3 2 3 1 3 1 3 1 1
 2 3 1 2 2 2 3 3 1 1 1 3 3 1 1 1 2 1 3 3 3 3 1 2 1 2 1 2 2 3 3 2 2 3 3 1 1
 3 1 3 2 1 3 1 2 1 3 1 2 1 1 1 3 3 1 2 2 2 1 2 3 2 2]


why numpy not lists

very fast

contigous memory

simd processing


effective cache

# getting started

In [6]:
import numpy as np

a=np.array([1,2,3])
b=np.array([1,2,3])
print (a*b)

[1 4 9]


In [7]:
a=np.array([1,2,3])
b=np.array([4])
print (a*b)

[ 4  8 12]


In [8]:
a=np.array([1,2,3])
b=np.array([5])
print (a*b)

[ 5 10 15]


In [9]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.ndim

1

In [11]:
a.shape

(3,)

In [12]:
b.shape

(1,)

In [13]:
c.shape

(2, 3)

In [14]:
c.ndim

2

In [15]:
a.dtype

dtype('int64')

In [16]:
b=np.array([1,2,3],dtype='int8')

In [17]:
b.dtype

dtype('int8')

In [18]:
a.itemsize

8

In [19]:
b.itemsize

1

In [20]:
a.size

3

In [21]:
c.size

6

In [22]:
c.itemsize

8

In [23]:
f"number of bytes in c={c.size*c.itemsize}"

'number of bytes in c=48'

In [24]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [25]:
a[1,-1]

12

In [26]:
a[1,5]

12

In [27]:
a[1,3]

10

In [28]:
a[0,-1]

6

In [29]:
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [30]:
a[:,3:6]

array([[ 4,  5,  6],
       [10, 11, 12]])

start:end:step
        

In [31]:
a[:,2:5:2]

array([[ 3,  5],
       [ 9, 11]])

In [32]:
a[1,-1]=20

In [33]:
a


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 20]])

In [34]:
a[:,2]=[1,2]

In [37]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20]])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros(5).itemsize

8

In [40]:
np.zeros(5,dtype='int32')

array([0, 0, 0, 0, 0], dtype=int32)

In [41]:
np.zeros(5,dtype='int32').itemsize

4

In [45]:
np.zeros(3,4,dtype=int)

TypeError: Argument given by name ('dtype') and position (2)

In [48]:
np.zeros((3,4),dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [49]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
np.ones((4,3,2),dtype="int8")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [51]:
np.full((2,2),99,dtype=int)

array([[99, 99],
       [99, 99]])

In [52]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.full_like(a,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [54]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [55]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
np.random.rand(3,3,3,3)

array([[[[0.08758059, 0.07314456, 0.96921747],
         [0.25274901, 0.87801829, 0.1338153 ],
         [0.50173338, 0.24799901, 0.65470672]],

        [[0.80308489, 0.77388446, 0.95436891],
         [0.10240004, 0.43582234, 0.96979068],
         [0.59038558, 0.09394713, 0.71672894]],

        [[0.47780103, 0.09452041, 0.41394185],
         [0.84725219, 0.12864719, 0.7059566 ],
         [0.80915412, 0.36492538, 0.59536568]]],


       [[[0.24785108, 0.50291116, 0.99682061],
         [0.6879425 , 0.63715663, 0.5341303 ],
         [0.09996669, 0.27802502, 0.71658777]],

        [[0.78493937, 0.09047013, 0.10593928],
         [0.67080216, 0.14177134, 0.89421732],
         [0.21401025, 0.73451044, 0.08856956]],

        [[0.57215822, 0.51026777, 0.78614135],
         [0.97192442, 0.90802469, 0.24562896],
         [0.6294939 , 0.48667799, 0.14781754]]],


       [[[0.37989656, 0.79906226, 0.03873322],
         [0.65649704, 0.6232684 , 0.69099913],
         [0.08132779, 0.43665335, 0.32142469

In [57]:
np.random.rand(3,3)

array([[0.00454311, 0.11317018, 0.99694971],
       [0.75473955, 0.02398842, 0.00949023],
       [0.10300132, 0.43668421, 0.65195542]])

In [58]:
np.random.random_sample(a.shape)

array([[0.51470342, 0.46128721, 0.777747  , 0.78032015, 0.16159447,
        0.04977922],
       [0.23544774, 0.84366378, 0.98682466, 0.30901325, 0.08328948,
        0.62637359]])

In [59]:
np.random.randint(0,1)

0

In [60]:
np.random.randint(0,1)

0

In [61]:
np.random.randint(0,1)

0

In [62]:
np.random.randint(4,size=(3,4))

array([[1, 3, 3, 2],
       [1, 1, 2, 1],
       [0, 0, 0, 1]])

In [63]:
np.random.randint(4,8,size=(3,4))

array([[5, 7, 6, 6],
       [4, 6, 4, 4],
       [4, 6, 7, 4]])

In [64]:
np.random.randint(0,1)

0

In [65]:
np.random.randint(0,1)

0

In [66]:
np.random.randint(0,1)

0

In [67]:
np.random.randint(0,1)

0

In [68]:
np.random.randint(0,1)

0

In [69]:
np.random.randint(0,1)

0

In [70]:
np.random.randint(0,1)

0

In [71]:
np.random.randint(0,1)

0

In [72]:
np.random.randint(0,2)

1

In [73]:
np.random.randint(0,2)

0

In [74]:
np.random.randint(0,2)

1

end is not inclusive

In [75]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [76]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
ar=np.repeat(a,3)

In [78]:
ar

array([ 1,  1,  1,  2,  2,  2,  1,  1,  1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  2,  2,  2, 10, 10, 10, 11, 11, 11, 20,
       20, 20])

In [79]:
ar=np.repeat(a,3,axis=0)

In [80]:
ar

array([[ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20]])

In [81]:
a.shape

(2, 6)

In [82]:
np.repeat(a,6,axis=0)

array([[ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20],
       [ 7,  8,  2, 10, 11, 20]])

In [83]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  8,  2, 10, 11, 20]])

In [84]:
np.repeat(a,3)

array([ 1,  1,  1,  2,  2,  2,  1,  1,  1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  2,  2,  2, 10, 10, 10, 11, 11, 11, 20,
       20, 20])

In [85]:
a=np.ones((5,5),dtype=int)


In [86]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [87]:
b=np.zeros((3,3),dtype=int)

In [88]:
b[1,1]=9

In [89]:
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [90]:
a[1:-1,1:-1]=b

In [91]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [92]:
b=a


In [93]:
b[0,0]=5


In [94]:
a

array([[5, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [95]:
a=np.array([1,2,3])
print(a+2)

[3 4 5]


In [96]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

##### linear algebra

In [98]:
a=np.ones((2,3))

In [99]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [101]:
b=np.ones((3,2))*2

In [102]:
b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [103]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [105]:
np.linalg.det(np.matmul(a,b))

0.0

In [106]:
np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

In [107]:
np.linalg.pinv(a)

array([[0.16666667, 0.16666667],
       [0.16666667, 0.16666667],
       [0.16666667, 0.16666667]])

In [108]:
np.linalg.eig(a)

LinAlgError: Last 2 dimensions of the array must be square

In [112]:
a=np.ones((3,3))

In [113]:
np.linalg.eig(a)

(array([-2.22044605e-16,  3.00000000e+00,  0.00000000e+00]),
 array([[-0.81649658,  0.57735027,  0.        ],
        [ 0.40824829,  0.57735027, -0.70710678],
        [ 0.40824829,  0.57735027,  0.70710678]]))

In [115]:
a=[[1,2,3],[4,5,6]]
np.min(a)

1

In [116]:
np.max(a)

6

In [125]:
a=np.repeat(a,1)

In [119]:
a

array([1, 2, 3, 4, 5, 6])

In [126]:
np.random.choice(a)

1

In [127]:
np.random.choice(a)

5

In [128]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

# reorganising array

In [131]:
a=np.array([[1,2,3],[4,5,6]])

In [132]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

hstack vstack

np.genfrom(txt)

# boolean indexing

In [136]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [137]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [138]:
a[a>4]

array([5, 6, 7, 8, 9])

In [139]:
a[[2,-1,3]]

array([3, 9, 4])